wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1700032266.197478
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      - 23
      4: 3.11.5
      5: 0.15.12
      6: 4.32.1
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
